### ISSUE TITLE
Changes to `pb_initialize_import` in next version of Pressbooks

### ISSUE THREAD

**Issue by dac514** [lumenlearning/candela-utility#10]
### Description 

We've made changes to the `pb_initialize_import` filter. The old one was buggy. It only let one 3rd party importer, the last loaded, work at time. It would override all the others. Old code:

`$importer = apply_filters( 'pb_initialize_import', null );`

New code:
 > https://github.com/pressbooks/pressbooks/blob/3fe31d85b46b46b6da8df7229716e50f55b6f776/inc/modules/import/class-import.php#L312

As you can hopefully see from the new code, we've done it in way that if you only have one extra importer on your PB install, everything will work the way it did before. We're essentially supporting broken behaviour to minimize impact on existing installs. 

_Right now, as I type, any PB with more than one 3rd party importer is broken._

My request is that when PB5 is released, please change your code to:

```
add_action( 'pb_initialize_import', function ( $a ) {
    $a[] = \Candela\Utility\Modules\Import\IMSCC\IMSCC::init();
    return $a;
} );

// ...

class IMSCC extends Import {
    CONST TYPE_OF = 'imscc';
    // ...
}
```

Thanks.

### System Information
- Candela Utility; v0.4.0
- Pressbooks: 5.0.0 (or dev branch)
- WordPress: 4.9.2

**Comment by ghost** [comment]
Resolved in latest release (1.0)
