### ISSUE TITLE
Declare compatibility with Pressbooks

### ISSUE THREAD

**Issue by dac514** [lumenlearning/candela-utility#11]
Please add: `Pressbooks tested up to: 5.0.2`

Or similar to your plugin? More info:

 + https://pressbooks.org/blog/2018/03/05/declaring-your-plugins-compatibility-with-pressbooks/

Thanks!

**Comment by ghost** [comment]
No prob.  Will queue this up for our next deploy.

Requested change [here](https://github.com/lumenlearning/candela-utility/commit/debacd71cadfd4e182a7c4ad609f1e608e8a220a).

**Comment by ghost** [comment]
Resolved in latest release (1.0)
